### PR TITLE
Add header line for running the exporter as Python3 program directly

### PR DESCRIPTION
**Pull request by gabrieleiannetti**
Hi,

to execute the exporter directly I have added the required line as the header into the exporter program.

It has at least 2 reasons:

    It is the main entry point and should be executable directly without involving the interpreter directly
    We can run it directly for testing, ...

I assumed, that the exporter will run at least with version 3, so I specified explicitly.
Would not keep compatibility with version 2 anyway, so I think it is a good call here.

What do you think, will you merge it into the master?

Best
Gabriele

### CODE REVIEW

**Comment by guilbaults** [comment]
Hi, this is done in the specfile, the main intention was to keep compatibility with Centos 7 with the RPMs in EPEL by installing `python2-prometheus_client` instead of requiring a pip install. 

This should also work with Centos 8 with `python3-prometheus_client` and a different specfile.

**Comment by gabrieleiannetti** [comment]
I am not installing any package here, since I would like to modify the program...

**Comment by guilbaults** [comment]
I will modify the existing specfile so it does not conflict with the python3 shebang.

**Comment by gabrieleiannetti** [comment]
Would be nice to run the program right away...

You could probably drop that lines in the specfile, if you would merge my pull request:

```
sed -i -e '1i#!/usr/bin/python' infiniband-exporter.py
install -m 0755 %{name}.py %{buildroot}/%{_bindir}/%{name}
```

**Pull request merged**
